const actionType = {
    DUMMY_FETCH : 'DUMMY_FETCH',
    REGISTER_STATUS: 'REGISTER_STATUS',
    REGISTER_ACCOUNTHOLDER_STATUS: 'REGISTER_ACCOUNTHOLDER_STATUS',
    LOGIN_STATUS: 'LOGIN_STATUS',
    ADD_PROFILE: 'ADD_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    JWT: 'JWT',
    ADD_CHECKINGS: 'ADD_CHECKINGS',
    UPDATE_CHECKINGS: 'UPDATE_CHECKINGS',
    ADD_SAVINGS: 'ADD_SAVINGS',
    UPDATE_SAVINGS: 'UPDATE_SAVINGSSAVINGS',
    ADD_CDS: 'ADD_CDS',
    UPDATE_CDS: 'UPDATE_CDS',
    LOG_OUT: 'LOG_OUT'
};

export default actionType;